# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-29 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('testimony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
